name: proto
description: "Prototype project for my car"
publish_to: 'none'

version: 0.0.1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #Navigation
  go_router: ^13.2.4

  #Notifications
  flutter_local_notifications: ^17.1.0

  #For generate sha salt auth key
  crypto: ^3.0.3

  #For save local data
  shared_preferences: ^2.2.3

  #Style
  google_fonts: ^6.2.1
  image_picker: ^1.1.0
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.3.1
  provider: ^6.1.2
  easy_localization: ^3.0.6

  uicons: ^1.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - lib/
    - lib/generated/
    - lib/Application/
    - lib/Application/Providers/
    - lib/Application/Style/
    - lib/Application/Config/
    - lib/Application/Router/
    - lib/Application/Screens/
    - lib/Application/Screens/Start/
    - lib/Application/Screens/Splash/


